# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Slack for Non-Humans™ - Machine-first CLI for Slack"
  homepage "https://github.com/kehao95/slack-agent-cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.4/slk_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "2ad347e376617962c4556683c2bc961e6162c725e12ea3a21b63dc4a792b80a7"

      def install
        bin.install "slk"
      end
    end
    on_arm do
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.4/slk_0.1.4_Darwin_arm64.tar.gz"
      sha256 "1595341e202ebd8120e6c01e24032d00c6d7144e2dd07604d34020313998939a"

      def install
        bin.install "slk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.4/slk_0.1.4_Linux_x86_64.tar.gz"
        sha256 "41d8ee4a98ec6ef958e09b552c315638d7de511de68d91d96c5fbbd3994de3ab"

        def install
          bin.install "slk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.4/slk_0.1.4_Linux_arm64.tar.gz"
        sha256 "4167b3ee776691e6d5708d2ec0cb916a9680dce6fdca11b8e1c90de10ba02407"

        def install
          bin.install "slk"
        end
      end
    end
  end
end
