# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Slack for Non-Humans™ - Machine-first CLI for Slack"
  homepage "https://github.com/kehao95/slack-agent-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.1/slk_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "5330b0667b48c504c4324888b55ecfa46ab7af95302fb127e3022c4ec8bc1e41"

      def install
        bin.install "slk"
      end
    end
    on_arm do
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.1/slk_0.1.1_Darwin_arm64.tar.gz"
      sha256 "189c99a80f134bd6f2128c48aca966032be6d1a824f8ed7d4d4a1bb330fa3ba3"

      def install
        bin.install "slk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.1/slk_0.1.1_Linux_x86_64.tar.gz"
        sha256 "45c1c0dc3517977fa9c4df9541c5183f4116b5e78631079cd53df088771623d2"

        def install
          bin.install "slk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.1/slk_0.1.1_Linux_arm64.tar.gz"
        sha256 "1c6e2453449122ddf3fa2c4c0d70f65b7770cf1a6aaa348875537bbf2727acbd"

        def install
          bin.install "slk"
        end
      end
    end
  end
end
