# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Slack for Non-Humans™ - Machine-first CLI for Slack"
  homepage "https://github.com/kehao95/slack-agent-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.0/slk_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "ae6c7ece0cc5a59ee9259471ed457bc619b0777f280e48a33aa92f78f3b4f8ee"

      def install
        bin.install "slk"
      end
    end
    on_arm do
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.0/slk_0.1.0_Darwin_arm64.tar.gz"
      sha256 "f1d44f07838b17100e65dff76cf0619b0fbc44e988970717acfc540ee6473636"

      def install
        bin.install "slk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.0/slk_0.1.0_Linux_x86_64.tar.gz"
        sha256 "222debe5eb5898a0bdeb1ae1dac23f5b4895164028cb3c1bfa2a757ef80552cd"

        def install
          bin.install "slk"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.1.0/slk_0.1.0_Linux_arm64.tar.gz"
        sha256 "bfd749784fbbc21c6085f9b101192adbc06165a5f7f81ca902ec3a33645c925a"

        def install
          bin.install "slk"
        end
      end
    end
  end
end
