# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slk < Formula
  desc "Slack for Non-Humans™ - Machine-first CLI for Slack"
  homepage "https://github.com/kehao95/slack-agent-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.0.1/slack-agent-cli_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "d1df398c960009d9b526def31e0944daa3a70836f63648cebd9033c03f3ef08f"

      def install
        bin.install "slk"
      end
    end
    on_arm do
      url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.0.1/slack-agent-cli_0.0.1_Darwin_arm64.tar.gz"
      sha256 "6fb452daebf83a2c8bd9166685157d370fac27e12147867d0c43a113a074d05e"

      def install
        bin.install "slk"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.0.1/slack-agent-cli_0.0.1_Linux_x86_64.tar.gz"
        sha256 "04664c42c461c9538d9bd6dfad9237bbf929a24b14d32b1d0c571fb65da661d5"

        def install
          bin.install "slack-agent-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kehao95/slack-agent-cli/releases/download/v0.0.1/slack-agent-cli_0.0.1_Linux_arm64.tar.gz"
        sha256 "f8002ca7683ce6ccaed1a2d7eedbf0840eae4c38446b672cf5d42560d0e1fde1"

        def install
          bin.install "slack-agent-cli"
        end
      end
    end
  end
end
